version: '3.8'
services:
  backend:
    build: ./server
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - optNetwork
    volumes:
      - ./server/media:/var/www/media # /var/www/media:/var/www/media
    env_file:
      - ./server/.env
    depends_on:
      - postgresql-db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
    command: ["npm", "start"]
    networks:
      - optNetwork
    ports:
      - "3000:3000"
    restart: always

  postgresql-db:
    image: postgres:15-alpine
    env_file:
      - ./postgres-config/.pg-env
    networks:
      - optNetwork
    volumes:
      - ./postgres-config/database_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
  
  nginx:
    build:
      context: ./nginx
    networks:
      - optNetwork
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    restart: always

networks:
  optNetwork: