"""revised order item model 2

Revision ID: 047776bccbf5
Revises: 33e2a99ef211
Create Date: 2023-09-03 21:57:48.433918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047776bccbf5'
down_revision = '33e2a99ef211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
