"""added default to status

Revision ID: 17df633840b1
Revises: 4403a75cfaa8
Create Date: 2023-08-27 19:47:56.099924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17df633840b1'
down_revision = '4403a75cfaa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
