"""revised category model

Revision ID: 1e958d437e75
Revises: d28c317a9970
Create Date: 2023-09-03 18:40:01.388283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e958d437e75'
down_revision = 'd28c317a9970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.String(), server_default='/Products/placeholder-image.png', nullable=True))
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
