"""refactored products model, deleted inventory model

Revision ID: 223969d7e3c8
Revises: d5762d98d660
Create Date: 2023-08-30 17:26:16.572107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '223969d7e3c8'
down_revision = 'd5762d98d660'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_id', table_name='inventory')
    op.drop_table('inventory')
    op.add_column('products', sa.Column('sizes', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('products', 'article',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'weight',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               nullable=False)
    op.alter_column('products', 'product_origin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'sub_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sub_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'product_origin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'weight',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'article',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'sizes')
    op.create_table('inventory',
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='inventory_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_pkey')
    )
    op.create_index('ix_inventory_id', 'inventory', ['id'], unique=False)
    # ### end Alembic commands ###
