"""added slug to some models

Revision ID: 3bb72360d82b
Revises: da7c3882d984
Create Date: 2023-09-08 10:07:50.672157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb72360d82b'
down_revision = 'da7c3882d984'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug_en', sa.String(), nullable=True))
    op.drop_column('categories', 'href')
    op.add_column('products', sa.Column('slug_en', sa.String(), nullable=True))
    op.add_column('sub', sa.Column('slug_en', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub', 'slug_en')
    op.drop_column('products', 'slug_en')
    op.add_column('categories', sa.Column('href', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'slug_en')
    # ### end Alembic commands ###
