"""revision #don know

Revision ID: 3d86dd4f22b8
Revises: 223969d7e3c8
Create Date: 2023-08-30 18:14:27.360139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d86dd4f22b8'
down_revision = '223969d7e3c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
