"""refactored models with nullable

Revision ID: 59f3ef377d5c
Revises: cb97dd4ca8da
Create Date: 2023-08-29 17:46:09.186876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f3ef377d5c'
down_revision = 'cb97dd4ca8da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'href',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('content', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               nullable=False,
               existing_server_default=sa.text("'1'::numeric"))
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'sub_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sub', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('sub', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'sub_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'base_price',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               nullable=True,
               existing_server_default=sa.text("'1'::numeric"))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'href',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
