"""added back_populates to product-inventory relationship

Revision ID: 95ebded71393
Revises: fd9178c373c1
Create Date: 2023-08-13 13:47:10.347465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ebded71393'
down_revision = 'fd9178c373c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
