"""added back_populates to product-inventory relationship

Revision ID: a8faba467b88
Revises: 95ebded71393
Create Date: 2023-08-13 13:49:53.209567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8faba467b88'
down_revision = '95ebded71393'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
