"""added img_url to product model

Revision ID: a8ffbb56cfac
Revises: a8faba467b88
Create Date: 2023-08-13 23:27:33.020535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ffbb56cfac'
down_revision = 'a8faba467b88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'img_url')
    # ### end Alembic commands ###
