"""added route mapping model

Revision ID: b80258bac66f
Revises: be3c2800299a
Create Date: 2023-09-08 14:31:55.715714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80258bac66f'
down_revision = 'be3c2800299a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_mapping',
    sa.Column('slug_en', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug_en')
    )
    op.create_index(op.f('ix_route_mapping_id'), 'route_mapping', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_mapping_id'), table_name='route_mapping')
    op.drop_table('route_mapping')
    # ### end Alembic commands ###
