"""adjusted product & orderItem relationship 2

Revision ID: be3c2800299a
Revises: f3267c513d7a
Create Date: 2023-09-08 11:23:38.845574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3c2800299a'
down_revision = 'f3267c513d7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
