"""revised order and orderItem models

Revision ID: d28c317a9970
Revises: 3d86dd4f22b8
Create Date: 2023-09-03 17:07:15.165526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28c317a9970'
down_revision = '3d86dd4f22b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price')
    op.drop_column('order_items', 'size')
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False))
    op.drop_column('orders', 'paid')
    op.drop_column('orders', 'returned')
    op.drop_column('orders', 'delivered')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivered', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('returned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'status')
    op.add_column('order_items', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('order_items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
