"""refactored models with nullable

Revision ID: d5762d98d660
Revises: 59f3ef377d5c
Create Date: 2023-08-29 17:51:28.408479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5762d98d660'
down_revision = '59f3ef377d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
