"""created page content model

Revision ID: da7c3882d984
Revises: 9bedc358d8a2
Create Date: 2023-09-06 20:24:05.541879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7c3882d984'
down_revision = '9bedc358d8a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_content',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('paragraph1', sa.Text(), nullable=True),
    sa.Column('paragraph2', sa.Text(), nullable=True),
    sa.Column('paragraph3', sa.Text(), nullable=True),
    sa.Column('header1', sa.String(), nullable=True),
    sa.Column('body1', sa.String(), nullable=True),
    sa.Column('header2', sa.String(), nullable=True),
    sa.Column('body2', sa.String(), nullable=True),
    sa.Column('header3', sa.String(), nullable=True),
    sa.Column('body3', sa.String(), nullable=True),
    sa.Column('header4', sa.String(), nullable=True),
    sa.Column('body4', sa.String(), nullable=True),
    sa.Column('header5', sa.String(), nullable=True),
    sa.Column('body5', sa.String(), nullable=True),
    sa.Column('header6', sa.String(), nullable=True),
    sa.Column('body6', sa.String(), nullable=True),
    sa.Column('header7', sa.String(), nullable=True),
    sa.Column('body7', sa.String(), nullable=True),
    sa.Column('backgroundImage', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_content_id'), 'page_content', ['id'], unique=False)
    op.create_index(op.f('ix_page_content_title'), 'page_content', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_content_title'), table_name='page_content')
    op.drop_index(op.f('ix_page_content_id'), table_name='page_content')
    op.drop_table('page_content')
    # ### end Alembic commands ###
