"""added sub to product model

Revision ID: ee331ab4c7b8
Revises: 26ef898ad515
Create Date: 2023-08-24 09:55:06.932677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee331ab4c7b8'
down_revision = '26ef898ad515'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
