"""adjusted product & orderItem relationship

Revision ID: f3267c513d7a
Revises: 8595f3c81166
Create Date: 2023-09-08 11:21:17.303917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3267c513d7a'
down_revision = '8595f3c81166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
