"""added cascade delete to product-inventory relationship

Revision ID: fd9178c373c1
Revises: 0344729545cc
Create Date: 2023-08-13 13:36:04.210049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9178c373c1'
down_revision = '0344729545cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
